//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureObservation) DeepCopyInto(out *FeatureObservation) {
	*out = *in
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = new(string)
		**out = **in
	}
	if in.FeatureDescription != nil {
		in, out := &in.FeatureDescription, &out.FeatureDescription
		*out = new(string)
		**out = **in
	}
	if in.FeatureName != nil {
		in, out := &in.FeatureName, &out.FeatureName
		*out = new(string)
		**out = **in
	}
	if in.Permission != nil {
		in, out := &in.Permission, &out.Permission
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureObservation.
func (in *FeatureObservation) DeepCopy() *FeatureObservation {
	if in == nil {
		return nil
	}
	out := new(FeatureObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureParameters) DeepCopyInto(out *FeatureParameters) {
	*out = *in
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = new(string)
		**out = **in
	}
	if in.Permission != nil {
		in, out := &in.Permission, &out.Permission
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureParameters.
func (in *FeatureParameters) DeepCopy() *FeatureParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapServerObservation) DeepCopyInto(out *LdapServerObservation) {
	*out = *in
	if in.BindIdentity != nil {
		in, out := &in.BindIdentity, &out.BindIdentity
		*out = new(string)
		**out = **in
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UseStarttls != nil {
		in, out := &in.UseStarttls, &out.UseStarttls
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapServerObservation.
func (in *LdapServerObservation) DeepCopy() *LdapServerObservation {
	if in == nil {
		return nil
	}
	out := new(LdapServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapServerParameters) DeepCopyInto(out *LdapServerParameters) {
	*out = *in
	if in.BindIdentity != nil {
		in, out := &in.BindIdentity, &out.BindIdentity
		*out = new(string)
		**out = **in
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UseStarttls != nil {
		in, out := &in.UseStarttls, &out.UseStarttls
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapServerParameters.
func (in *LdapServerParameters) DeepCopy() *LdapServerParameters {
	if in == nil {
		return nil
	}
	out := new(LdapServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUser) DeepCopyInto(out *NodeUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUser.
func (in *NodeUser) DeepCopy() *NodeUser {
	if in == nil {
		return nil
	}
	out := new(NodeUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUserList) DeepCopyInto(out *NodeUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUserList.
func (in *NodeUserList) DeepCopy() *NodeUserList {
	if in == nil {
		return nil
	}
	out := new(NodeUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUserObservation) DeepCopyInto(out *NodeUserObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.FullName != nil {
		in, out := &in.FullName, &out.FullName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastPasswordChange != nil {
		in, out := &in.LastPasswordChange, &out.LastPasswordChange
		*out = new(float64)
		**out = **in
	}
	if in.PasswordChangeFrequency != nil {
		in, out := &in.PasswordChangeFrequency, &out.PasswordChangeFrequency
		*out = new(float64)
		**out = **in
	}
	if in.PasswordChangeWarning != nil {
		in, out := &in.PasswordChangeWarning, &out.PasswordChangeWarning
		*out = new(float64)
		**out = **in
	}
	if in.PasswordResetRequired != nil {
		in, out := &in.PasswordResetRequired, &out.PasswordResetRequired
		*out = new(bool)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(float64)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUserObservation.
func (in *NodeUserObservation) DeepCopy() *NodeUserObservation {
	if in == nil {
		return nil
	}
	out := new(NodeUserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUserParameters) DeepCopyInto(out *NodeUserParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.FullName != nil {
		in, out := &in.FullName, &out.FullName
		*out = new(string)
		**out = **in
	}
	if in.PasswordChangeFrequency != nil {
		in, out := &in.PasswordChangeFrequency, &out.PasswordChangeFrequency
		*out = new(float64)
		**out = **in
	}
	if in.PasswordChangeWarning != nil {
		in, out := &in.PasswordChangeWarning, &out.PasswordChangeWarning
		*out = new(float64)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUserParameters.
func (in *NodeUserParameters) DeepCopy() *NodeUserParameters {
	if in == nil {
		return nil
	}
	out := new(NodeUserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUserSpec) DeepCopyInto(out *NodeUserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUserSpec.
func (in *NodeUserSpec) DeepCopy() *NodeUserSpec {
	if in == nil {
		return nil
	}
	out := new(NodeUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUserStatus) DeepCopyInto(out *NodeUserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUserStatus.
func (in *NodeUserStatus) DeepCopy() *NodeUserStatus {
	if in == nil {
		return nil
	}
	out := new(NodeUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySource) DeepCopyInto(out *PolicyLdapIdentitySource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySource.
func (in *PolicyLdapIdentitySource) DeepCopy() *PolicyLdapIdentitySource {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyLdapIdentitySource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySourceList) DeepCopyInto(out *PolicyLdapIdentitySourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyLdapIdentitySource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySourceList.
func (in *PolicyLdapIdentitySourceList) DeepCopy() *PolicyLdapIdentitySourceList {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyLdapIdentitySourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySourceObservation) DeepCopyInto(out *PolicyLdapIdentitySourceObservation) {
	*out = *in
	if in.AlternativeDomainNames != nil {
		in, out := &in.AlternativeDomainNames, &out.AlternativeDomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapServer != nil {
		in, out := &in.LdapServer, &out.LdapServer
		*out = make([]LdapServerObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySourceObservation.
func (in *PolicyLdapIdentitySourceObservation) DeepCopy() *PolicyLdapIdentitySourceObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySourceParameters) DeepCopyInto(out *PolicyLdapIdentitySourceParameters) {
	*out = *in
	if in.AlternativeDomainNames != nil {
		in, out := &in.AlternativeDomainNames, &out.AlternativeDomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.LdapServer != nil {
		in, out := &in.LdapServer, &out.LdapServer
		*out = make([]LdapServerParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySourceParameters.
func (in *PolicyLdapIdentitySourceParameters) DeepCopy() *PolicyLdapIdentitySourceParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySourceSpec) DeepCopyInto(out *PolicyLdapIdentitySourceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySourceSpec.
func (in *PolicyLdapIdentitySourceSpec) DeepCopy() *PolicyLdapIdentitySourceSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLdapIdentitySourceStatus) DeepCopyInto(out *PolicyLdapIdentitySourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLdapIdentitySourceStatus.
func (in *PolicyLdapIdentitySourceStatus) DeepCopy() *PolicyLdapIdentitySourceStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyLdapIdentitySourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRole) DeepCopyInto(out *PolicyUserManagementRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRole.
func (in *PolicyUserManagementRole) DeepCopy() *PolicyUserManagementRole {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyUserManagementRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBinding) DeepCopyInto(out *PolicyUserManagementRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBinding.
func (in *PolicyUserManagementRoleBinding) DeepCopy() *PolicyUserManagementRoleBinding {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyUserManagementRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingList) DeepCopyInto(out *PolicyUserManagementRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyUserManagementRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingList.
func (in *PolicyUserManagementRoleBindingList) DeepCopy() *PolicyUserManagementRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyUserManagementRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingObservation) DeepCopyInto(out *PolicyUserManagementRoleBindingObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentitySourceID != nil {
		in, out := &in.IdentitySourceID, &out.IdentitySourceID
		*out = new(string)
		**out = **in
	}
	if in.IdentitySourceType != nil {
		in, out := &in.IdentitySourceType, &out.IdentitySourceType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OverwriteLocalUser != nil {
		in, out := &in.OverwriteLocalUser, &out.OverwriteLocalUser
		*out = new(bool)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.RolesForPath != nil {
		in, out := &in.RolesForPath, &out.RolesForPath
		*out = make([]RolesForPathObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyUserManagementRoleBindingTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingObservation.
func (in *PolicyUserManagementRoleBindingObservation) DeepCopy() *PolicyUserManagementRoleBindingObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingParameters) DeepCopyInto(out *PolicyUserManagementRoleBindingParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IdentitySourceID != nil {
		in, out := &in.IdentitySourceID, &out.IdentitySourceID
		*out = new(string)
		**out = **in
	}
	if in.IdentitySourceType != nil {
		in, out := &in.IdentitySourceType, &out.IdentitySourceType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OverwriteLocalUser != nil {
		in, out := &in.OverwriteLocalUser, &out.OverwriteLocalUser
		*out = new(bool)
		**out = **in
	}
	if in.RolesForPath != nil {
		in, out := &in.RolesForPath, &out.RolesForPath
		*out = make([]RolesForPathParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyUserManagementRoleBindingTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingParameters.
func (in *PolicyUserManagementRoleBindingParameters) DeepCopy() *PolicyUserManagementRoleBindingParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingSpec) DeepCopyInto(out *PolicyUserManagementRoleBindingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingSpec.
func (in *PolicyUserManagementRoleBindingSpec) DeepCopy() *PolicyUserManagementRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingStatus) DeepCopyInto(out *PolicyUserManagementRoleBindingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingStatus.
func (in *PolicyUserManagementRoleBindingStatus) DeepCopy() *PolicyUserManagementRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingTagObservation) DeepCopyInto(out *PolicyUserManagementRoleBindingTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingTagObservation.
func (in *PolicyUserManagementRoleBindingTagObservation) DeepCopy() *PolicyUserManagementRoleBindingTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleBindingTagParameters) DeepCopyInto(out *PolicyUserManagementRoleBindingTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleBindingTagParameters.
func (in *PolicyUserManagementRoleBindingTagParameters) DeepCopy() *PolicyUserManagementRoleBindingTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleBindingTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleList) DeepCopyInto(out *PolicyUserManagementRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyUserManagementRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleList.
func (in *PolicyUserManagementRoleList) DeepCopy() *PolicyUserManagementRoleList {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyUserManagementRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleObservation) DeepCopyInto(out *PolicyUserManagementRoleObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = make([]FeatureObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyUserManagementRoleTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleObservation.
func (in *PolicyUserManagementRoleObservation) DeepCopy() *PolicyUserManagementRoleObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleParameters) DeepCopyInto(out *PolicyUserManagementRoleParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = make([]FeatureParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyUserManagementRoleTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleParameters.
func (in *PolicyUserManagementRoleParameters) DeepCopy() *PolicyUserManagementRoleParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleSpec) DeepCopyInto(out *PolicyUserManagementRoleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleSpec.
func (in *PolicyUserManagementRoleSpec) DeepCopy() *PolicyUserManagementRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleStatus) DeepCopyInto(out *PolicyUserManagementRoleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleStatus.
func (in *PolicyUserManagementRoleStatus) DeepCopy() *PolicyUserManagementRoleStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleTagObservation) DeepCopyInto(out *PolicyUserManagementRoleTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleTagObservation.
func (in *PolicyUserManagementRoleTagObservation) DeepCopy() *PolicyUserManagementRoleTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUserManagementRoleTagParameters) DeepCopyInto(out *PolicyUserManagementRoleTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUserManagementRoleTagParameters.
func (in *PolicyUserManagementRoleTagParameters) DeepCopy() *PolicyUserManagementRoleTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyUserManagementRoleTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentity) DeepCopyInto(out *PrincipalIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentity.
func (in *PrincipalIdentity) DeepCopy() *PrincipalIdentity {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrincipalIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityList) DeepCopyInto(out *PrincipalIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrincipalIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityList.
func (in *PrincipalIdentityList) DeepCopy() *PrincipalIdentityList {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrincipalIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityObservation) DeepCopyInto(out *PrincipalIdentityObservation) {
	*out = *in
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CertificatePem != nil {
		in, out := &in.CertificatePem, &out.CertificatePem
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsProtected != nil {
		in, out := &in.IsProtected, &out.IsProtected
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeID != nil {
		in, out := &in.NodeID, &out.NodeID
		*out = new(string)
		**out = **in
	}
	if in.RolesForPath != nil {
		in, out := &in.RolesForPath, &out.RolesForPath
		*out = make([]PrincipalIdentityRolesForPathObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PrincipalIdentityTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityObservation.
func (in *PrincipalIdentityObservation) DeepCopy() *PrincipalIdentityObservation {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityParameters) DeepCopyInto(out *PrincipalIdentityParameters) {
	*out = *in
	if in.CertificatePem != nil {
		in, out := &in.CertificatePem, &out.CertificatePem
		*out = new(string)
		**out = **in
	}
	if in.IsProtected != nil {
		in, out := &in.IsProtected, &out.IsProtected
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeID != nil {
		in, out := &in.NodeID, &out.NodeID
		*out = new(string)
		**out = **in
	}
	if in.RolesForPath != nil {
		in, out := &in.RolesForPath, &out.RolesForPath
		*out = make([]PrincipalIdentityRolesForPathParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PrincipalIdentityTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityParameters.
func (in *PrincipalIdentityParameters) DeepCopy() *PrincipalIdentityParameters {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityRolesForPathObservation) DeepCopyInto(out *PrincipalIdentityRolesForPathObservation) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityRolesForPathObservation.
func (in *PrincipalIdentityRolesForPathObservation) DeepCopy() *PrincipalIdentityRolesForPathObservation {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityRolesForPathObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityRolesForPathParameters) DeepCopyInto(out *PrincipalIdentityRolesForPathParameters) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityRolesForPathParameters.
func (in *PrincipalIdentityRolesForPathParameters) DeepCopy() *PrincipalIdentityRolesForPathParameters {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityRolesForPathParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentitySpec) DeepCopyInto(out *PrincipalIdentitySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentitySpec.
func (in *PrincipalIdentitySpec) DeepCopy() *PrincipalIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityStatus) DeepCopyInto(out *PrincipalIdentityStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityStatus.
func (in *PrincipalIdentityStatus) DeepCopy() *PrincipalIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityTagObservation) DeepCopyInto(out *PrincipalIdentityTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityTagObservation.
func (in *PrincipalIdentityTagObservation) DeepCopy() *PrincipalIdentityTagObservation {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalIdentityTagParameters) DeepCopyInto(out *PrincipalIdentityTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalIdentityTagParameters.
func (in *PrincipalIdentityTagParameters) DeepCopy() *PrincipalIdentityTagParameters {
	if in == nil {
		return nil
	}
	out := new(PrincipalIdentityTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolesForPathObservation) DeepCopyInto(out *RolesForPathObservation) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolesForPathObservation.
func (in *RolesForPathObservation) DeepCopy() *RolesForPathObservation {
	if in == nil {
		return nil
	}
	out := new(RolesForPathObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolesForPathParameters) DeepCopyInto(out *RolesForPathParameters) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolesForPathParameters.
func (in *RolesForPathParameters) DeepCopy() *RolesForPathParameters {
	if in == nil {
		return nil
	}
	out := new(RolesForPathParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagObservation) DeepCopyInto(out *TagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagObservation.
func (in *TagObservation) DeepCopy() *TagObservation {
	if in == nil {
		return nil
	}
	out := new(TagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagParameters) DeepCopyInto(out *TagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagParameters.
func (in *TagParameters) DeepCopy() *TagParameters {
	if in == nil {
		return nil
	}
	out := new(TagParameters)
	in.DeepCopyInto(out)
	return out
}
