/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyDistributedFloodProtectionProfileBindingContextObservation struct {

	// Id of the project which the resource belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type PolicyDistributedFloodProtectionProfileBindingContextParameters struct {

	// Id of the project which the resource belongs to.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`
}

type PolicyDistributedFloodProtectionProfileBindingObservation struct {

	// Resource context
	Context []PolicyDistributedFloodProtectionProfileBindingContextObservation `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The path of the group to bind with the flood protection profile
	GroupPath *string `json:"groupPath,omitempty" tf:"group_path,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The path of the flood protection profile
	ProfilePath *string `json:"profilePath,omitempty" tf:"profile_path,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Sequence number of this profile binding
	SequenceNumber *float64 `json:"sequenceNumber,omitempty" tf:"sequence_number,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []PolicyDistributedFloodProtectionProfileBindingTagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDistributedFloodProtectionProfileBindingParameters struct {

	// Resource context
	// +kubebuilder:validation:Optional
	Context []PolicyDistributedFloodProtectionProfileBindingContextParameters `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The path of the group to bind with the flood protection profile
	// +kubebuilder:validation:Optional
	GroupPath *string `json:"groupPath,omitempty" tf:"group_path,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// The path of the flood protection profile
	// +kubebuilder:validation:Optional
	ProfilePath *string `json:"profilePath,omitempty" tf:"profile_path,omitempty"`

	// Sequence number of this profile binding
	// +kubebuilder:validation:Optional
	SequenceNumber *float64 `json:"sequenceNumber,omitempty" tf:"sequence_number,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []PolicyDistributedFloodProtectionProfileBindingTagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDistributedFloodProtectionProfileBindingTagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDistributedFloodProtectionProfileBindingTagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyDistributedFloodProtectionProfileBindingSpec defines the desired state of PolicyDistributedFloodProtectionProfileBinding
type PolicyDistributedFloodProtectionProfileBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyDistributedFloodProtectionProfileBindingParameters `json:"forProvider"`
}

// PolicyDistributedFloodProtectionProfileBindingStatus defines the observed state of PolicyDistributedFloodProtectionProfileBinding.
type PolicyDistributedFloodProtectionProfileBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyDistributedFloodProtectionProfileBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDistributedFloodProtectionProfileBinding is the Schema for the PolicyDistributedFloodProtectionProfileBindings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyDistributedFloodProtectionProfileBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.groupPath)",message="groupPath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.profilePath)",message="profilePath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.sequenceNumber)",message="sequenceNumber is a required parameter"
	Spec   PolicyDistributedFloodProtectionProfileBindingSpec   `json:"spec"`
	Status PolicyDistributedFloodProtectionProfileBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDistributedFloodProtectionProfileBindingList contains a list of PolicyDistributedFloodProtectionProfileBindings
type PolicyDistributedFloodProtectionProfileBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyDistributedFloodProtectionProfileBinding `json:"items"`
}

// Repository type metadata.
var (
	PolicyDistributedFloodProtectionProfileBinding_Kind             = "PolicyDistributedFloodProtectionProfileBinding"
	PolicyDistributedFloodProtectionProfileBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyDistributedFloodProtectionProfileBinding_Kind}.String()
	PolicyDistributedFloodProtectionProfileBinding_KindAPIVersion   = PolicyDistributedFloodProtectionProfileBinding_Kind + "." + CRDGroupVersion.String()
	PolicyDistributedFloodProtectionProfileBinding_GroupVersionKind = CRDGroupVersion.WithKind(PolicyDistributedFloodProtectionProfileBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyDistributedFloodProtectionProfileBinding{}, &PolicyDistributedFloodProtectionProfileBindingList{})
}
