/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyLbIcmpMonitorProfileObservation struct {

	// The data size (in byte) of the ICMP healthcheck packet
	DataLength *float64 `json:"dataLength,omitempty" tf:"data_length,omitempty"`

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Number of consecutive checks that must fail before marking it down
	FallCount *float64 `json:"fallCount,omitempty" tf:"fall_count,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The frequency at which the system issues the monitor check (in seconds)
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Number of consecutive checks that must pass before marking it up
	RiseCount *float64 `json:"riseCount,omitempty" tf:"rise_count,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []PolicyLbIcmpMonitorProfileTagObservation `json:"tag,omitempty" tf:"tag,omitempty"`

	// Number of seconds the target has to respond to the monitor request
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type PolicyLbIcmpMonitorProfileParameters struct {

	// The data size (in byte) of the ICMP healthcheck packet
	// +kubebuilder:validation:Optional
	DataLength *float64 `json:"dataLength,omitempty" tf:"data_length,omitempty"`

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Number of consecutive checks that must fail before marking it down
	// +kubebuilder:validation:Optional
	FallCount *float64 `json:"fallCount,omitempty" tf:"fall_count,omitempty"`

	// The frequency at which the system issues the monitor check (in seconds)
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Number of consecutive checks that must pass before marking it up
	// +kubebuilder:validation:Optional
	RiseCount *float64 `json:"riseCount,omitempty" tf:"rise_count,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []PolicyLbIcmpMonitorProfileTagParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// Number of seconds the target has to respond to the monitor request
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type PolicyLbIcmpMonitorProfileTagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyLbIcmpMonitorProfileTagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyLbIcmpMonitorProfileSpec defines the desired state of PolicyLbIcmpMonitorProfile
type PolicyLbIcmpMonitorProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyLbIcmpMonitorProfileParameters `json:"forProvider"`
}

// PolicyLbIcmpMonitorProfileStatus defines the observed state of PolicyLbIcmpMonitorProfile.
type PolicyLbIcmpMonitorProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyLbIcmpMonitorProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyLbIcmpMonitorProfile is the Schema for the PolicyLbIcmpMonitorProfiles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyLbIcmpMonitorProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	Spec   PolicyLbIcmpMonitorProfileSpec   `json:"spec"`
	Status PolicyLbIcmpMonitorProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyLbIcmpMonitorProfileList contains a list of PolicyLbIcmpMonitorProfiles
type PolicyLbIcmpMonitorProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyLbIcmpMonitorProfile `json:"items"`
}

// Repository type metadata.
var (
	PolicyLbIcmpMonitorProfile_Kind             = "PolicyLbIcmpMonitorProfile"
	PolicyLbIcmpMonitorProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyLbIcmpMonitorProfile_Kind}.String()
	PolicyLbIcmpMonitorProfile_KindAPIVersion   = PolicyLbIcmpMonitorProfile_Kind + "." + CRDGroupVersion.String()
	PolicyLbIcmpMonitorProfile_GroupVersionKind = CRDGroupVersion.WithKind(PolicyLbIcmpMonitorProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyLbIcmpMonitorProfile{}, &PolicyLbIcmpMonitorProfileList{})
}
