/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CPUConfigObservation struct {

	// Number of Logical cpu cores (Lcores) to be placed on a specified NUMA node
	NumLcores *float64 `json:"numLcores,omitempty" tf:"num_lcores,omitempty"`

	// Unique index of the Non Uniform Memory Access (NUMA) node
	NumaNodeIndex *float64 `json:"numaNodeIndex,omitempty" tf:"numa_node_index,omitempty"`
}

type CPUConfigParameters struct {

	// Number of Logical cpu cores (Lcores) to be placed on a specified NUMA node
	// +kubebuilder:validation:Required
	NumLcores *float64 `json:"numLcores" tf:"num_lcores,omitempty"`

	// Unique index of the Non Uniform Memory Access (NUMA) node
	// +kubebuilder:validation:Required
	NumaNodeIndex *float64 `json:"numaNodeIndex" tf:"numa_node_index,omitempty"`
}

type HostSwitchConfigOptionIPAssignmentObservation struct {

	// Enables DHCP assignment
	AssignedByDHCP *bool `json:"assignedByDhcp,omitempty" tf:"assigned_by_dhcp,omitempty"`

	// IP assignment specification for Static IP List.
	StaticIP []HostSwitchConfigOptionIPAssignmentStaticIPObservation `json:"staticIp,omitempty" tf:"static_ip,omitempty"`

	// IP assignment specification for Static IP Pool
	StaticIPPool *string `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type HostSwitchConfigOptionIPAssignmentParameters struct {

	// Enables DHCP assignment
	// +kubebuilder:validation:Optional
	AssignedByDHCP *bool `json:"assignedByDhcp,omitempty" tf:"assigned_by_dhcp,omitempty"`

	// IP assignment specification for Static IP List.
	// +kubebuilder:validation:Optional
	StaticIP []HostSwitchConfigOptionIPAssignmentStaticIPParameters `json:"staticIp,omitempty" tf:"static_ip,omitempty"`

	// IP assignment specification for Static IP Pool
	// +kubebuilder:validation:Optional
	StaticIPPool *string `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type HostSwitchConfigOptionIPAssignmentStaticIPObservation struct {

	// Gateway IP
	DefaultGateway *string `json:"defaultGateway,omitempty" tf:"default_gateway,omitempty"`

	// List of IPs for transport node host switch virtual tunnel endpoints
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// Subnet mask
	SubnetMask *string `json:"subnetMask,omitempty" tf:"subnet_mask,omitempty"`
}

type HostSwitchConfigOptionIPAssignmentStaticIPParameters struct {

	// Gateway IP
	// +kubebuilder:validation:Required
	DefaultGateway *string `json:"defaultGateway" tf:"default_gateway,omitempty"`

	// List of IPs for transport node host switch virtual tunnel endpoints
	// +kubebuilder:validation:Required
	IPAddresses []*string `json:"ipAddresses" tf:"ip_addresses,omitempty"`

	// Subnet mask
	// +kubebuilder:validation:Required
	SubnetMask *string `json:"subnetMask" tf:"subnet_mask,omitempty"`
}

type HostSwitchConfigOptionObservation struct {

	// The host switch id. This ID will be used to reference a host switch
	HostSwitchID *string `json:"hostSwitchId,omitempty" tf:"host_switch_id,omitempty"`

	// Identifiers of host switch profiles to be associated with this host switch
	HostSwitchProfile []*string `json:"hostSwitchProfile,omitempty" tf:"host_switch_profile,omitempty"`

	// Specification for IPs to be used with host switch virtual tunnel endpoints
	IPAssignment []HostSwitchConfigOptionIPAssignmentObservation `json:"ipAssignment,omitempty" tf:"ip_assignment,omitempty"`

	// Uplink/LAG of VMware vSphere Distributed Switch connected to the HostSwitch
	Uplink []UplinkObservation `json:"uplink,omitempty" tf:"uplink,omitempty"`
}

type HostSwitchConfigOptionParameters struct {

	// The host switch id. This ID will be used to reference a host switch
	// +kubebuilder:validation:Optional
	HostSwitchID *string `json:"hostSwitchId,omitempty" tf:"host_switch_id,omitempty"`

	// Identifiers of host switch profiles to be associated with this host switch
	// +kubebuilder:validation:Optional
	HostSwitchProfile []*string `json:"hostSwitchProfile,omitempty" tf:"host_switch_profile,omitempty"`

	// Specification for IPs to be used with host switch virtual tunnel endpoints
	// +kubebuilder:validation:Optional
	IPAssignment []HostSwitchConfigOptionIPAssignmentParameters `json:"ipAssignment,omitempty" tf:"ip_assignment,omitempty"`

	// Uplink/LAG of VMware vSphere Distributed Switch connected to the HostSwitch
	// +kubebuilder:validation:Optional
	Uplink []UplinkParameters `json:"uplink,omitempty" tf:"uplink,omitempty"`
}

type IPAssignmentStaticIPObservation struct {

	// Gateway IP
	DefaultGateway *string `json:"defaultGateway,omitempty" tf:"default_gateway,omitempty"`

	// List of IPs for transport node host switch virtual tunnel endpoints
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// Subnet mask
	SubnetMask *string `json:"subnetMask,omitempty" tf:"subnet_mask,omitempty"`
}

type IPAssignmentStaticIPParameters struct {

	// Gateway IP
	// +kubebuilder:validation:Required
	DefaultGateway *string `json:"defaultGateway" tf:"default_gateway,omitempty"`

	// List of IPs for transport node host switch virtual tunnel endpoints
	// +kubebuilder:validation:Required
	IPAddresses []*string `json:"ipAddresses" tf:"ip_addresses,omitempty"`

	// Subnet mask
	// +kubebuilder:validation:Required
	SubnetMask *string `json:"subnetMask" tf:"subnet_mask,omitempty"`
}

type PolicyHostTransportNodeObservation struct {

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Discovered node id to create Host Transport Node
	DiscoveredNodeID *string `json:"discoveredNodeId,omitempty" tf:"discovered_node_id,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// ID of the enforcement point this Host Transport Node belongs to
	EnforcementPoint *string `json:"enforcementPoint,omitempty" tf:"enforcement_point,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Indicate whether NSX service should be removed from hypervisor during resource deletion
	RemoveNsxOnDestroy *bool `json:"removeNsxOnDestroy,omitempty" tf:"remove_nsx_on_destroy,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Path to the site this Host Transport Node belongs to
	SitePath *string `json:"sitePath,omitempty" tf:"site_path,omitempty"`

	// Standard host switch specification
	StandardHostSwitch []PolicyHostTransportNodeStandardHostSwitchObservation `json:"standardHostSwitch,omitempty" tf:"standard_host_switch,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []PolicyHostTransportNodeTagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyHostTransportNodeParameters struct {

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Discovered node id to create Host Transport Node
	// +kubebuilder:validation:Optional
	DiscoveredNodeID *string `json:"discoveredNodeId,omitempty" tf:"discovered_node_id,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// ID of the enforcement point this Host Transport Node belongs to
	// +kubebuilder:validation:Optional
	EnforcementPoint *string `json:"enforcementPoint,omitempty" tf:"enforcement_point,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Indicate whether NSX service should be removed from hypervisor during resource deletion
	// +kubebuilder:validation:Optional
	RemoveNsxOnDestroy *bool `json:"removeNsxOnDestroy,omitempty" tf:"remove_nsx_on_destroy,omitempty"`

	// Path to the site this Host Transport Node belongs to
	// +kubebuilder:validation:Optional
	SitePath *string `json:"sitePath,omitempty" tf:"site_path,omitempty"`

	// Standard host switch specification
	// +kubebuilder:validation:Optional
	StandardHostSwitch []PolicyHostTransportNodeStandardHostSwitchParameters `json:"standardHostSwitch,omitempty" tf:"standard_host_switch,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []PolicyHostTransportNodeTagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyHostTransportNodeStandardHostSwitchObservation struct {

	// Enhanced Networking Stack enabled HostSwitch CPU configuration
	CPUConfig []CPUConfigObservation `json:"cpuConfig,omitempty" tf:"cpu_config,omitempty"`

	// The host switch id. This ID will be used to reference a host switch
	HostSwitchID *string `json:"hostSwitchId,omitempty" tf:"host_switch_id,omitempty"`

	// Operational mode of a HostSwitch
	HostSwitchMode *string `json:"hostSwitchMode,omitempty" tf:"host_switch_mode,omitempty"`

	// Host switch name. This name will be used to reference a host switch
	HostSwitchName *string `json:"hostSwitchName,omitempty" tf:"host_switch_name,omitempty"`

	// Identifiers of host switch profiles to be associated with this host switch
	HostSwitchProfile []*string `json:"hostSwitchProfile,omitempty" tf:"host_switch_profile,omitempty"`

	// Specification for IPs to be used with host switch virtual tunnel endpoints
	IPAssignment []StandardHostSwitchIPAssignmentObservation `json:"ipAssignment,omitempty" tf:"ip_assignment,omitempty"`

	// Migrate any pnics which are in use
	IsMigratePnics *bool `json:"isMigratePnics,omitempty" tf:"is_migrate_pnics,omitempty"`

	// Physical NICs connected to the host switch
	Pnic []StandardHostSwitchPnicObservation `json:"pnic,omitempty" tf:"pnic,omitempty"`

	// Transport Node Profile sub-configuration Options
	TransportNodeProfileSubConfig []TransportNodeProfileSubConfigObservation `json:"transportNodeProfileSubConfig,omitempty" tf:"transport_node_profile_sub_config,omitempty"`

	// Transport zone endpoints
	TransportZoneEndpoint []StandardHostSwitchTransportZoneEndpointObservation `json:"transportZoneEndpoint,omitempty" tf:"transport_zone_endpoint,omitempty"`

	// Uplink/LAG of VMware vSphere Distributed Switch connected to the HostSwitch
	Uplink []StandardHostSwitchUplinkObservation `json:"uplink,omitempty" tf:"uplink,omitempty"`

	// The vmknic and logical switch mappings
	VmkInstallMigration []VmkInstallMigrationObservation `json:"vmkInstallMigration,omitempty" tf:"vmk_install_migration,omitempty"`
}

type PolicyHostTransportNodeStandardHostSwitchParameters struct {

	// Enhanced Networking Stack enabled HostSwitch CPU configuration
	// +kubebuilder:validation:Optional
	CPUConfig []CPUConfigParameters `json:"cpuConfig,omitempty" tf:"cpu_config,omitempty"`

	// The host switch id. This ID will be used to reference a host switch
	// +kubebuilder:validation:Optional
	HostSwitchID *string `json:"hostSwitchId,omitempty" tf:"host_switch_id,omitempty"`

	// Operational mode of a HostSwitch
	// +kubebuilder:validation:Optional
	HostSwitchMode *string `json:"hostSwitchMode,omitempty" tf:"host_switch_mode,omitempty"`

	// Host switch name. This name will be used to reference a host switch
	// +kubebuilder:validation:Optional
	HostSwitchName *string `json:"hostSwitchName,omitempty" tf:"host_switch_name,omitempty"`

	// Identifiers of host switch profiles to be associated with this host switch
	// +kubebuilder:validation:Optional
	HostSwitchProfile []*string `json:"hostSwitchProfile,omitempty" tf:"host_switch_profile,omitempty"`

	// Specification for IPs to be used with host switch virtual tunnel endpoints
	// +kubebuilder:validation:Required
	IPAssignment []StandardHostSwitchIPAssignmentParameters `json:"ipAssignment" tf:"ip_assignment,omitempty"`

	// Migrate any pnics which are in use
	// +kubebuilder:validation:Optional
	IsMigratePnics *bool `json:"isMigratePnics,omitempty" tf:"is_migrate_pnics,omitempty"`

	// Physical NICs connected to the host switch
	// +kubebuilder:validation:Optional
	Pnic []StandardHostSwitchPnicParameters `json:"pnic,omitempty" tf:"pnic,omitempty"`

	// Transport Node Profile sub-configuration Options
	// +kubebuilder:validation:Optional
	TransportNodeProfileSubConfig []TransportNodeProfileSubConfigParameters `json:"transportNodeProfileSubConfig,omitempty" tf:"transport_node_profile_sub_config,omitempty"`

	// Transport zone endpoints
	// +kubebuilder:validation:Optional
	TransportZoneEndpoint []StandardHostSwitchTransportZoneEndpointParameters `json:"transportZoneEndpoint,omitempty" tf:"transport_zone_endpoint,omitempty"`

	// Uplink/LAG of VMware vSphere Distributed Switch connected to the HostSwitch
	// +kubebuilder:validation:Optional
	Uplink []StandardHostSwitchUplinkParameters `json:"uplink,omitempty" tf:"uplink,omitempty"`

	// The vmknic and logical switch mappings
	// +kubebuilder:validation:Optional
	VmkInstallMigration []VmkInstallMigrationParameters `json:"vmkInstallMigration,omitempty" tf:"vmk_install_migration,omitempty"`
}

type PolicyHostTransportNodeTagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyHostTransportNodeTagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type StandardHostSwitchIPAssignmentObservation struct {

	// Enables DHCP assignment
	AssignedByDHCP *bool `json:"assignedByDhcp,omitempty" tf:"assigned_by_dhcp,omitempty"`

	// IP assignment specification for Static IP List.
	StaticIP []IPAssignmentStaticIPObservation `json:"staticIp,omitempty" tf:"static_ip,omitempty"`

	// IP assignment specification for Static IP Pool
	StaticIPPool *string `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type StandardHostSwitchIPAssignmentParameters struct {

	// Enables DHCP assignment
	// +kubebuilder:validation:Optional
	AssignedByDHCP *bool `json:"assignedByDhcp,omitempty" tf:"assigned_by_dhcp,omitempty"`

	// IP assignment specification for Static IP List.
	// +kubebuilder:validation:Optional
	StaticIP []IPAssignmentStaticIPParameters `json:"staticIp,omitempty" tf:"static_ip,omitempty"`

	// IP assignment specification for Static IP Pool
	// +kubebuilder:validation:Optional
	StaticIPPool *string `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type StandardHostSwitchPnicObservation struct {

	// Device name or key
	DeviceName *string `json:"deviceName,omitempty" tf:"device_name,omitempty"`

	// Uplink name for this Pnic
	UplinkName *string `json:"uplinkName,omitempty" tf:"uplink_name,omitempty"`
}

type StandardHostSwitchPnicParameters struct {

	// Device name or key
	// +kubebuilder:validation:Required
	DeviceName *string `json:"deviceName" tf:"device_name,omitempty"`

	// Uplink name for this Pnic
	// +kubebuilder:validation:Required
	UplinkName *string `json:"uplinkName" tf:"uplink_name,omitempty"`
}

type StandardHostSwitchTransportZoneEndpointObservation struct {

	// Unique ID identifying the transport zone for this endpoint
	TransportZone *string `json:"transportZone,omitempty" tf:"transport_zone,omitempty"`

	// Identifiers of the transport zone profiles associated with this transport zone endpoint on this transport node
	TransportZoneProfiles []*string `json:"transportZoneProfiles,omitempty" tf:"transport_zone_profiles,omitempty"`
}

type StandardHostSwitchTransportZoneEndpointParameters struct {

	// Unique ID identifying the transport zone for this endpoint
	// +kubebuilder:validation:Required
	TransportZone *string `json:"transportZone" tf:"transport_zone,omitempty"`

	// Identifiers of the transport zone profiles associated with this transport zone endpoint on this transport node
	// +kubebuilder:validation:Optional
	TransportZoneProfiles []*string `json:"transportZoneProfiles,omitempty" tf:"transport_zone_profiles,omitempty"`
}

type StandardHostSwitchUplinkObservation struct {

	// Uplink name from UplinkHostSwitch profile
	UplinkName *string `json:"uplinkName,omitempty" tf:"uplink_name,omitempty"`

	// Link Aggregation Group (LAG) name of Virtual Distributed Switch
	VdsLagName *string `json:"vdsLagName,omitempty" tf:"vds_lag_name,omitempty"`

	// Uplink name of VMware vSphere Distributed Switch (VDS)
	VdsUplinkName *string `json:"vdsUplinkName,omitempty" tf:"vds_uplink_name,omitempty"`
}

type StandardHostSwitchUplinkParameters struct {

	// Uplink name from UplinkHostSwitch profile
	// +kubebuilder:validation:Required
	UplinkName *string `json:"uplinkName" tf:"uplink_name,omitempty"`

	// Link Aggregation Group (LAG) name of Virtual Distributed Switch
	// +kubebuilder:validation:Optional
	VdsLagName *string `json:"vdsLagName,omitempty" tf:"vds_lag_name,omitempty"`

	// Uplink name of VMware vSphere Distributed Switch (VDS)
	// +kubebuilder:validation:Optional
	VdsUplinkName *string `json:"vdsUplinkName,omitempty" tf:"vds_uplink_name,omitempty"`
}

type TransportNodeProfileSubConfigObservation struct {

	// Subset of the host switch configuration
	HostSwitchConfigOption []HostSwitchConfigOptionObservation `json:"hostSwitchConfigOption,omitempty" tf:"host_switch_config_option,omitempty"`

	// Name of the transport node profile config option
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TransportNodeProfileSubConfigParameters struct {

	// Subset of the host switch configuration
	// +kubebuilder:validation:Required
	HostSwitchConfigOption []HostSwitchConfigOptionParameters `json:"hostSwitchConfigOption" tf:"host_switch_config_option,omitempty"`

	// Name of the transport node profile config option
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`
}

type UplinkObservation struct {

	// Uplink name from UplinkHostSwitch profile
	UplinkName *string `json:"uplinkName,omitempty" tf:"uplink_name,omitempty"`

	// Link Aggregation Group (LAG) name of Virtual Distributed Switch
	VdsLagName *string `json:"vdsLagName,omitempty" tf:"vds_lag_name,omitempty"`

	// Uplink name of VMware vSphere Distributed Switch (VDS)
	VdsUplinkName *string `json:"vdsUplinkName,omitempty" tf:"vds_uplink_name,omitempty"`
}

type UplinkParameters struct {

	// Uplink name from UplinkHostSwitch profile
	// +kubebuilder:validation:Required
	UplinkName *string `json:"uplinkName" tf:"uplink_name,omitempty"`

	// Link Aggregation Group (LAG) name of Virtual Distributed Switch
	// +kubebuilder:validation:Optional
	VdsLagName *string `json:"vdsLagName,omitempty" tf:"vds_lag_name,omitempty"`

	// Uplink name of VMware vSphere Distributed Switch (VDS)
	// +kubebuilder:validation:Optional
	VdsUplinkName *string `json:"vdsUplinkName,omitempty" tf:"vds_uplink_name,omitempty"`
}

type VmkInstallMigrationObservation struct {

	// The network id to which the ESX vmk interface will be migrated
	DestinationNetwork *string `json:"destinationNetwork,omitempty" tf:"destination_network,omitempty"`

	// ESX vmk interface name
	DeviceName *string `json:"deviceName,omitempty" tf:"device_name,omitempty"`
}

type VmkInstallMigrationParameters struct {

	// The network id to which the ESX vmk interface will be migrated
	// +kubebuilder:validation:Required
	DestinationNetwork *string `json:"destinationNetwork" tf:"destination_network,omitempty"`

	// ESX vmk interface name
	// +kubebuilder:validation:Required
	DeviceName *string `json:"deviceName" tf:"device_name,omitempty"`
}

// PolicyHostTransportNodeSpec defines the desired state of PolicyHostTransportNode
type PolicyHostTransportNodeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyHostTransportNodeParameters `json:"forProvider"`
}

// PolicyHostTransportNodeStatus defines the observed state of PolicyHostTransportNode.
type PolicyHostTransportNodeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyHostTransportNodeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyHostTransportNode is the Schema for the PolicyHostTransportNodes API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyHostTransportNode struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.discoveredNodeId)",message="discoveredNodeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.standardHostSwitch)",message="standardHostSwitch is a required parameter"
	Spec   PolicyHostTransportNodeSpec   `json:"spec"`
	Status PolicyHostTransportNodeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyHostTransportNodeList contains a list of PolicyHostTransportNodes
type PolicyHostTransportNodeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyHostTransportNode `json:"items"`
}

// Repository type metadata.
var (
	PolicyHostTransportNode_Kind             = "PolicyHostTransportNode"
	PolicyHostTransportNode_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyHostTransportNode_Kind}.String()
	PolicyHostTransportNode_KindAPIVersion   = PolicyHostTransportNode_Kind + "." + CRDGroupVersion.String()
	PolicyHostTransportNode_GroupVersionKind = CRDGroupVersion.WithKind(PolicyHostTransportNode_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyHostTransportNode{}, &PolicyHostTransportNodeList{})
}
