/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContextObservation struct {

	// Id of the project which the resource belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type ContextParameters struct {

	// Id of the project which the resource belongs to.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`
}

type PolicyShareObservation struct {

	// Resource context
	Context []ContextObservation `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Path of the context
	SharedWith []*string `json:"sharedWith,omitempty" tf:"shared_with,omitempty"`

	// Sharing Strategy
	SharingStrategy *string `json:"sharingStrategy,omitempty" tf:"sharing_strategy,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []PolicyShareTagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyShareParameters struct {

	// Resource context
	// +kubebuilder:validation:Optional
	Context []ContextParameters `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Path of the context
	// +kubebuilder:validation:Optional
	SharedWith []*string `json:"sharedWith,omitempty" tf:"shared_with,omitempty"`

	// Sharing Strategy
	// +kubebuilder:validation:Optional
	SharingStrategy *string `json:"sharingStrategy,omitempty" tf:"sharing_strategy,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []PolicyShareTagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyShareTagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyShareTagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyShareSpec defines the desired state of PolicyShare
type PolicyShareSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyShareParameters `json:"forProvider"`
}

// PolicyShareStatus defines the observed state of PolicyShare.
type PolicyShareStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyShareObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyShare is the Schema for the PolicyShares API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyShare struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.sharedWith)",message="sharedWith is a required parameter"
	Spec   PolicyShareSpec   `json:"spec"`
	Status PolicyShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyShareList contains a list of PolicyShares
type PolicyShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyShare `json:"items"`
}

// Repository type metadata.
var (
	PolicyShare_Kind             = "PolicyShare"
	PolicyShare_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyShare_Kind}.String()
	PolicyShare_KindAPIVersion   = PolicyShare_Kind + "." + CRDGroupVersion.String()
	PolicyShare_GroupVersionKind = CRDGroupVersion.WithKind(PolicyShare_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyShare{}, &PolicyShareList{})
}
