//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BypassRuleObservation) DeepCopyInto(out *BypassRuleObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BypassRuleObservation.
func (in *BypassRuleObservation) DeepCopy() *BypassRuleObservation {
	if in == nil {
		return nil
	}
	out := new(BypassRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BypassRuleParameters) DeepCopyInto(out *BypassRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BypassRuleParameters.
func (in *BypassRuleParameters) DeepCopy() *BypassRuleParameters {
	if in == nil {
		return nil
	}
	out := new(BypassRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfile) DeepCopyInto(out *PolicyIpsecVpnDpdProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfile.
func (in *PolicyIpsecVpnDpdProfile) DeepCopy() *PolicyIpsecVpnDpdProfile {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnDpdProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfileList) DeepCopyInto(out *PolicyIpsecVpnDpdProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnDpdProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfileList.
func (in *PolicyIpsecVpnDpdProfileList) DeepCopy() *PolicyIpsecVpnDpdProfileList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnDpdProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfileObservation) DeepCopyInto(out *PolicyIpsecVpnDpdProfileObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DpdProbeInterval != nil {
		in, out := &in.DpdProbeInterval, &out.DpdProbeInterval
		*out = new(float64)
		**out = **in
	}
	if in.DpdProbeMode != nil {
		in, out := &in.DpdProbeMode, &out.DpdProbeMode
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RetryCount != nil {
		in, out := &in.RetryCount, &out.RetryCount
		*out = new(float64)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfileObservation.
func (in *PolicyIpsecVpnDpdProfileObservation) DeepCopy() *PolicyIpsecVpnDpdProfileObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfileParameters) DeepCopyInto(out *PolicyIpsecVpnDpdProfileParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DpdProbeInterval != nil {
		in, out := &in.DpdProbeInterval, &out.DpdProbeInterval
		*out = new(float64)
		**out = **in
	}
	if in.DpdProbeMode != nil {
		in, out := &in.DpdProbeMode, &out.DpdProbeMode
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.RetryCount != nil {
		in, out := &in.RetryCount, &out.RetryCount
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfileParameters.
func (in *PolicyIpsecVpnDpdProfileParameters) DeepCopy() *PolicyIpsecVpnDpdProfileParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfileSpec) DeepCopyInto(out *PolicyIpsecVpnDpdProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfileSpec.
func (in *PolicyIpsecVpnDpdProfileSpec) DeepCopy() *PolicyIpsecVpnDpdProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnDpdProfileStatus) DeepCopyInto(out *PolicyIpsecVpnDpdProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnDpdProfileStatus.
func (in *PolicyIpsecVpnDpdProfileStatus) DeepCopy() *PolicyIpsecVpnDpdProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnDpdProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfile) DeepCopyInto(out *PolicyIpsecVpnIkeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfile.
func (in *PolicyIpsecVpnIkeProfile) DeepCopy() *PolicyIpsecVpnIkeProfile {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnIkeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileList) DeepCopyInto(out *PolicyIpsecVpnIkeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnIkeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileList.
func (in *PolicyIpsecVpnIkeProfileList) DeepCopy() *PolicyIpsecVpnIkeProfileList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnIkeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileObservation) DeepCopyInto(out *PolicyIpsecVpnIkeProfileObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DhGroups != nil {
		in, out := &in.DhGroups, &out.DhGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DigestAlgorithms != nil {
		in, out := &in.DigestAlgorithms, &out.DigestAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EncryptionAlgorithms != nil {
		in, out := &in.EncryptionAlgorithms, &out.EncryptionAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IkeVersion != nil {
		in, out := &in.IkeVersion, &out.IkeVersion
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.SaLifeTime != nil {
		in, out := &in.SaLifeTime, &out.SaLifeTime
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnIkeProfileTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileObservation.
func (in *PolicyIpsecVpnIkeProfileObservation) DeepCopy() *PolicyIpsecVpnIkeProfileObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileParameters) DeepCopyInto(out *PolicyIpsecVpnIkeProfileParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DhGroups != nil {
		in, out := &in.DhGroups, &out.DhGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DigestAlgorithms != nil {
		in, out := &in.DigestAlgorithms, &out.DigestAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EncryptionAlgorithms != nil {
		in, out := &in.EncryptionAlgorithms, &out.EncryptionAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IkeVersion != nil {
		in, out := &in.IkeVersion, &out.IkeVersion
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.SaLifeTime != nil {
		in, out := &in.SaLifeTime, &out.SaLifeTime
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnIkeProfileTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileParameters.
func (in *PolicyIpsecVpnIkeProfileParameters) DeepCopy() *PolicyIpsecVpnIkeProfileParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileSpec) DeepCopyInto(out *PolicyIpsecVpnIkeProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileSpec.
func (in *PolicyIpsecVpnIkeProfileSpec) DeepCopy() *PolicyIpsecVpnIkeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileStatus) DeepCopyInto(out *PolicyIpsecVpnIkeProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileStatus.
func (in *PolicyIpsecVpnIkeProfileStatus) DeepCopy() *PolicyIpsecVpnIkeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileTagObservation) DeepCopyInto(out *PolicyIpsecVpnIkeProfileTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileTagObservation.
func (in *PolicyIpsecVpnIkeProfileTagObservation) DeepCopy() *PolicyIpsecVpnIkeProfileTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnIkeProfileTagParameters) DeepCopyInto(out *PolicyIpsecVpnIkeProfileTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnIkeProfileTagParameters.
func (in *PolicyIpsecVpnIkeProfileTagParameters) DeepCopy() *PolicyIpsecVpnIkeProfileTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnIkeProfileTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpoint) DeepCopyInto(out *PolicyIpsecVpnLocalEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpoint.
func (in *PolicyIpsecVpnLocalEndpoint) DeepCopy() *PolicyIpsecVpnLocalEndpoint {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnLocalEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointList) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnLocalEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointList.
func (in *PolicyIpsecVpnLocalEndpointList) DeepCopy() *PolicyIpsecVpnLocalEndpointList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnLocalEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointObservation) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointObservation) {
	*out = *in
	if in.CertificatePath != nil {
		in, out := &in.CertificatePath, &out.CertificatePath
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LocalAddress != nil {
		in, out := &in.LocalAddress, &out.LocalAddress
		*out = new(string)
		**out = **in
	}
	if in.LocalID != nil {
		in, out := &in.LocalID, &out.LocalID
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnLocalEndpointTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustCAPaths != nil {
		in, out := &in.TrustCAPaths, &out.TrustCAPaths
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TrustCrlPaths != nil {
		in, out := &in.TrustCrlPaths, &out.TrustCrlPaths
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointObservation.
func (in *PolicyIpsecVpnLocalEndpointObservation) DeepCopy() *PolicyIpsecVpnLocalEndpointObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointParameters) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointParameters) {
	*out = *in
	if in.CertificatePath != nil {
		in, out := &in.CertificatePath, &out.CertificatePath
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.LocalAddress != nil {
		in, out := &in.LocalAddress, &out.LocalAddress
		*out = new(string)
		**out = **in
	}
	if in.LocalID != nil {
		in, out := &in.LocalID, &out.LocalID
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnLocalEndpointTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustCAPaths != nil {
		in, out := &in.TrustCAPaths, &out.TrustCAPaths
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TrustCrlPaths != nil {
		in, out := &in.TrustCrlPaths, &out.TrustCrlPaths
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointParameters.
func (in *PolicyIpsecVpnLocalEndpointParameters) DeepCopy() *PolicyIpsecVpnLocalEndpointParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointSpec) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointSpec.
func (in *PolicyIpsecVpnLocalEndpointSpec) DeepCopy() *PolicyIpsecVpnLocalEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointStatus) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointStatus.
func (in *PolicyIpsecVpnLocalEndpointStatus) DeepCopy() *PolicyIpsecVpnLocalEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointTagObservation) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointTagObservation.
func (in *PolicyIpsecVpnLocalEndpointTagObservation) DeepCopy() *PolicyIpsecVpnLocalEndpointTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnLocalEndpointTagParameters) DeepCopyInto(out *PolicyIpsecVpnLocalEndpointTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnLocalEndpointTagParameters.
func (in *PolicyIpsecVpnLocalEndpointTagParameters) DeepCopy() *PolicyIpsecVpnLocalEndpointTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnLocalEndpointTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnService) DeepCopyInto(out *PolicyIpsecVpnService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnService.
func (in *PolicyIpsecVpnService) DeepCopy() *PolicyIpsecVpnService {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceList) DeepCopyInto(out *PolicyIpsecVpnServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceList.
func (in *PolicyIpsecVpnServiceList) DeepCopy() *PolicyIpsecVpnServiceList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceObservation) DeepCopyInto(out *PolicyIpsecVpnServiceObservation) {
	*out = *in
	if in.BypassRule != nil {
		in, out := &in.BypassRule, &out.BypassRule
		*out = make([]BypassRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GatewayPath != nil {
		in, out := &in.GatewayPath, &out.GatewayPath
		*out = new(string)
		**out = **in
	}
	if in.HaSync != nil {
		in, out := &in.HaSync, &out.HaSync
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IkeLogLevel != nil {
		in, out := &in.IkeLogLevel, &out.IkeLogLevel
		*out = new(string)
		**out = **in
	}
	if in.LocaleServicePath != nil {
		in, out := &in.LocaleServicePath, &out.LocaleServicePath
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnServiceTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceObservation.
func (in *PolicyIpsecVpnServiceObservation) DeepCopy() *PolicyIpsecVpnServiceObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceParameters) DeepCopyInto(out *PolicyIpsecVpnServiceParameters) {
	*out = *in
	if in.BypassRule != nil {
		in, out := &in.BypassRule, &out.BypassRule
		*out = make([]BypassRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GatewayPath != nil {
		in, out := &in.GatewayPath, &out.GatewayPath
		*out = new(string)
		**out = **in
	}
	if in.HaSync != nil {
		in, out := &in.HaSync, &out.HaSync
		*out = new(bool)
		**out = **in
	}
	if in.IkeLogLevel != nil {
		in, out := &in.IkeLogLevel, &out.IkeLogLevel
		*out = new(string)
		**out = **in
	}
	if in.LocaleServicePath != nil {
		in, out := &in.LocaleServicePath, &out.LocaleServicePath
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnServiceTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceParameters.
func (in *PolicyIpsecVpnServiceParameters) DeepCopy() *PolicyIpsecVpnServiceParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceSpec) DeepCopyInto(out *PolicyIpsecVpnServiceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceSpec.
func (in *PolicyIpsecVpnServiceSpec) DeepCopy() *PolicyIpsecVpnServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceStatus) DeepCopyInto(out *PolicyIpsecVpnServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceStatus.
func (in *PolicyIpsecVpnServiceStatus) DeepCopy() *PolicyIpsecVpnServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceTagObservation) DeepCopyInto(out *PolicyIpsecVpnServiceTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceTagObservation.
func (in *PolicyIpsecVpnServiceTagObservation) DeepCopy() *PolicyIpsecVpnServiceTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnServiceTagParameters) DeepCopyInto(out *PolicyIpsecVpnServiceTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnServiceTagParameters.
func (in *PolicyIpsecVpnServiceTagParameters) DeepCopy() *PolicyIpsecVpnServiceTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnServiceTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSession) DeepCopyInto(out *PolicyIpsecVpnSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSession.
func (in *PolicyIpsecVpnSession) DeepCopy() *PolicyIpsecVpnSession {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionList) DeepCopyInto(out *PolicyIpsecVpnSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionList.
func (in *PolicyIpsecVpnSessionList) DeepCopy() *PolicyIpsecVpnSessionList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionObservation) DeepCopyInto(out *PolicyIpsecVpnSessionObservation) {
	*out = *in
	if in.AuthenticationMode != nil {
		in, out := &in.AuthenticationMode, &out.AuthenticationMode
		*out = new(string)
		**out = **in
	}
	if in.ComplianceSuite != nil {
		in, out := &in.ComplianceSuite, &out.ComplianceSuite
		*out = new(string)
		**out = **in
	}
	if in.ConnectionInitiationMode != nil {
		in, out := &in.ConnectionInitiationMode, &out.ConnectionInitiationMode
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DpdProfilePath != nil {
		in, out := &in.DpdProfilePath, &out.DpdProfilePath
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IkeProfilePath != nil {
		in, out := &in.IkeProfilePath, &out.IkeProfilePath
		*out = new(string)
		**out = **in
	}
	if in.LocalEndpointPath != nil {
		in, out := &in.LocalEndpointPath, &out.LocalEndpointPath
		*out = new(string)
		**out = **in
	}
	if in.MaxSegmentSize != nil {
		in, out := &in.MaxSegmentSize, &out.MaxSegmentSize
		*out = new(float64)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PeerAddress != nil {
		in, out := &in.PeerAddress, &out.PeerAddress
		*out = new(string)
		**out = **in
	}
	if in.PeerID != nil {
		in, out := &in.PeerID, &out.PeerID
		*out = new(string)
		**out = **in
	}
	if in.PrefixLength != nil {
		in, out := &in.PrefixLength, &out.PrefixLength
		*out = new(float64)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnSessionTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TunnelProfilePath != nil {
		in, out := &in.TunnelProfilePath, &out.TunnelProfilePath
		*out = new(string)
		**out = **in
	}
	if in.VPNType != nil {
		in, out := &in.VPNType, &out.VPNType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionObservation.
func (in *PolicyIpsecVpnSessionObservation) DeepCopy() *PolicyIpsecVpnSessionObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionParameters) DeepCopyInto(out *PolicyIpsecVpnSessionParameters) {
	*out = *in
	if in.AuthenticationMode != nil {
		in, out := &in.AuthenticationMode, &out.AuthenticationMode
		*out = new(string)
		**out = **in
	}
	if in.ComplianceSuite != nil {
		in, out := &in.ComplianceSuite, &out.ComplianceSuite
		*out = new(string)
		**out = **in
	}
	if in.ConnectionInitiationMode != nil {
		in, out := &in.ConnectionInitiationMode, &out.ConnectionInitiationMode
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DpdProfilePath != nil {
		in, out := &in.DpdProfilePath, &out.DpdProfilePath
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IkeProfilePath != nil {
		in, out := &in.IkeProfilePath, &out.IkeProfilePath
		*out = new(string)
		**out = **in
	}
	if in.LocalEndpointPath != nil {
		in, out := &in.LocalEndpointPath, &out.LocalEndpointPath
		*out = new(string)
		**out = **in
	}
	if in.MaxSegmentSize != nil {
		in, out := &in.MaxSegmentSize, &out.MaxSegmentSize
		*out = new(float64)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.PeerAddress != nil {
		in, out := &in.PeerAddress, &out.PeerAddress
		*out = new(string)
		**out = **in
	}
	if in.PeerID != nil {
		in, out := &in.PeerID, &out.PeerID
		*out = new(string)
		**out = **in
	}
	if in.PrefixLength != nil {
		in, out := &in.PrefixLength, &out.PrefixLength
		*out = new(float64)
		**out = **in
	}
	if in.PskSecretRef != nil {
		in, out := &in.PskSecretRef, &out.PskSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnSessionTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TunnelProfilePath != nil {
		in, out := &in.TunnelProfilePath, &out.TunnelProfilePath
		*out = new(string)
		**out = **in
	}
	if in.VPNType != nil {
		in, out := &in.VPNType, &out.VPNType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionParameters.
func (in *PolicyIpsecVpnSessionParameters) DeepCopy() *PolicyIpsecVpnSessionParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionSpec) DeepCopyInto(out *PolicyIpsecVpnSessionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionSpec.
func (in *PolicyIpsecVpnSessionSpec) DeepCopy() *PolicyIpsecVpnSessionSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionStatus) DeepCopyInto(out *PolicyIpsecVpnSessionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionStatus.
func (in *PolicyIpsecVpnSessionStatus) DeepCopy() *PolicyIpsecVpnSessionStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionTagObservation) DeepCopyInto(out *PolicyIpsecVpnSessionTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionTagObservation.
func (in *PolicyIpsecVpnSessionTagObservation) DeepCopy() *PolicyIpsecVpnSessionTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnSessionTagParameters) DeepCopyInto(out *PolicyIpsecVpnSessionTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnSessionTagParameters.
func (in *PolicyIpsecVpnSessionTagParameters) DeepCopy() *PolicyIpsecVpnSessionTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnSessionTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfile) DeepCopyInto(out *PolicyIpsecVpnTunnelProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfile.
func (in *PolicyIpsecVpnTunnelProfile) DeepCopy() *PolicyIpsecVpnTunnelProfile {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnTunnelProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileList) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyIpsecVpnTunnelProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileList.
func (in *PolicyIpsecVpnTunnelProfileList) DeepCopy() *PolicyIpsecVpnTunnelProfileList {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyIpsecVpnTunnelProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileObservation) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DfPolicy != nil {
		in, out := &in.DfPolicy, &out.DfPolicy
		*out = new(string)
		**out = **in
	}
	if in.DhGroups != nil {
		in, out := &in.DhGroups, &out.DhGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DigestAlgorithms != nil {
		in, out := &in.DigestAlgorithms, &out.DigestAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnablePerfectForwardSecrecy != nil {
		in, out := &in.EnablePerfectForwardSecrecy, &out.EnablePerfectForwardSecrecy
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionAlgorithms != nil {
		in, out := &in.EncryptionAlgorithms, &out.EncryptionAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.SaLifeTime != nil {
		in, out := &in.SaLifeTime, &out.SaLifeTime
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnTunnelProfileTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileObservation.
func (in *PolicyIpsecVpnTunnelProfileObservation) DeepCopy() *PolicyIpsecVpnTunnelProfileObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileParameters) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DfPolicy != nil {
		in, out := &in.DfPolicy, &out.DfPolicy
		*out = new(string)
		**out = **in
	}
	if in.DhGroups != nil {
		in, out := &in.DhGroups, &out.DhGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DigestAlgorithms != nil {
		in, out := &in.DigestAlgorithms, &out.DigestAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnablePerfectForwardSecrecy != nil {
		in, out := &in.EnablePerfectForwardSecrecy, &out.EnablePerfectForwardSecrecy
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionAlgorithms != nil {
		in, out := &in.EncryptionAlgorithms, &out.EncryptionAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.SaLifeTime != nil {
		in, out := &in.SaLifeTime, &out.SaLifeTime
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyIpsecVpnTunnelProfileTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileParameters.
func (in *PolicyIpsecVpnTunnelProfileParameters) DeepCopy() *PolicyIpsecVpnTunnelProfileParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileSpec) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileSpec.
func (in *PolicyIpsecVpnTunnelProfileSpec) DeepCopy() *PolicyIpsecVpnTunnelProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileStatus) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileStatus.
func (in *PolicyIpsecVpnTunnelProfileStatus) DeepCopy() *PolicyIpsecVpnTunnelProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileTagObservation) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileTagObservation.
func (in *PolicyIpsecVpnTunnelProfileTagObservation) DeepCopy() *PolicyIpsecVpnTunnelProfileTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIpsecVpnTunnelProfileTagParameters) DeepCopyInto(out *PolicyIpsecVpnTunnelProfileTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIpsecVpnTunnelProfileTagParameters.
func (in *PolicyIpsecVpnTunnelProfileTagParameters) DeepCopy() *PolicyIpsecVpnTunnelProfileTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyIpsecVpnTunnelProfileTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnService) DeepCopyInto(out *PolicyL2VpnService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnService.
func (in *PolicyL2VpnService) DeepCopy() *PolicyL2VpnService {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyL2VpnService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceList) DeepCopyInto(out *PolicyL2VpnServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyL2VpnService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceList.
func (in *PolicyL2VpnServiceList) DeepCopy() *PolicyL2VpnServiceList {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyL2VpnServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceObservation) DeepCopyInto(out *PolicyL2VpnServiceObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnableHub != nil {
		in, out := &in.EnableHub, &out.EnableHub
		*out = new(bool)
		**out = **in
	}
	if in.EncapIPPool != nil {
		in, out := &in.EncapIPPool, &out.EncapIPPool
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GatewayPath != nil {
		in, out := &in.GatewayPath, &out.GatewayPath
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LocaleServicePath != nil {
		in, out := &in.LocaleServicePath, &out.LocaleServicePath
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyL2VpnServiceTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceObservation.
func (in *PolicyL2VpnServiceObservation) DeepCopy() *PolicyL2VpnServiceObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceParameters) DeepCopyInto(out *PolicyL2VpnServiceParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnableHub != nil {
		in, out := &in.EnableHub, &out.EnableHub
		*out = new(bool)
		**out = **in
	}
	if in.EncapIPPool != nil {
		in, out := &in.EncapIPPool, &out.EncapIPPool
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GatewayPath != nil {
		in, out := &in.GatewayPath, &out.GatewayPath
		*out = new(string)
		**out = **in
	}
	if in.LocaleServicePath != nil {
		in, out := &in.LocaleServicePath, &out.LocaleServicePath
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyL2VpnServiceTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceParameters.
func (in *PolicyL2VpnServiceParameters) DeepCopy() *PolicyL2VpnServiceParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceSpec) DeepCopyInto(out *PolicyL2VpnServiceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceSpec.
func (in *PolicyL2VpnServiceSpec) DeepCopy() *PolicyL2VpnServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceStatus) DeepCopyInto(out *PolicyL2VpnServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceStatus.
func (in *PolicyL2VpnServiceStatus) DeepCopy() *PolicyL2VpnServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceTagObservation) DeepCopyInto(out *PolicyL2VpnServiceTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceTagObservation.
func (in *PolicyL2VpnServiceTagObservation) DeepCopy() *PolicyL2VpnServiceTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnServiceTagParameters) DeepCopyInto(out *PolicyL2VpnServiceTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnServiceTagParameters.
func (in *PolicyL2VpnServiceTagParameters) DeepCopy() *PolicyL2VpnServiceTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnServiceTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSession) DeepCopyInto(out *PolicyL2VpnSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSession.
func (in *PolicyL2VpnSession) DeepCopy() *PolicyL2VpnSession {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyL2VpnSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionList) DeepCopyInto(out *PolicyL2VpnSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyL2VpnSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionList.
func (in *PolicyL2VpnSessionList) DeepCopy() *PolicyL2VpnSessionList {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyL2VpnSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionObservation) DeepCopyInto(out *PolicyL2VpnSessionObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LocalAddress != nil {
		in, out := &in.LocalAddress, &out.LocalAddress
		*out = new(string)
		**out = **in
	}
	if in.MaxSegmentSize != nil {
		in, out := &in.MaxSegmentSize, &out.MaxSegmentSize
		*out = new(float64)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PeerAddress != nil {
		in, out := &in.PeerAddress, &out.PeerAddress
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyL2VpnSessionTagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransportTunnels != nil {
		in, out := &in.TransportTunnels, &out.TransportTunnels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionObservation.
func (in *PolicyL2VpnSessionObservation) DeepCopy() *PolicyL2VpnSessionObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionParameters) DeepCopyInto(out *PolicyL2VpnSessionParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LocalAddress != nil {
		in, out := &in.LocalAddress, &out.LocalAddress
		*out = new(string)
		**out = **in
	}
	if in.MaxSegmentSize != nil {
		in, out := &in.MaxSegmentSize, &out.MaxSegmentSize
		*out = new(float64)
		**out = **in
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.PeerAddress != nil {
		in, out := &in.PeerAddress, &out.PeerAddress
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]PolicyL2VpnSessionTagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransportTunnels != nil {
		in, out := &in.TransportTunnels, &out.TransportTunnels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionParameters.
func (in *PolicyL2VpnSessionParameters) DeepCopy() *PolicyL2VpnSessionParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionSpec) DeepCopyInto(out *PolicyL2VpnSessionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionSpec.
func (in *PolicyL2VpnSessionSpec) DeepCopy() *PolicyL2VpnSessionSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionStatus) DeepCopyInto(out *PolicyL2VpnSessionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionStatus.
func (in *PolicyL2VpnSessionStatus) DeepCopy() *PolicyL2VpnSessionStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionTagObservation) DeepCopyInto(out *PolicyL2VpnSessionTagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionTagObservation.
func (in *PolicyL2VpnSessionTagObservation) DeepCopy() *PolicyL2VpnSessionTagObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyL2VpnSessionTagParameters) DeepCopyInto(out *PolicyL2VpnSessionTagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyL2VpnSessionTagParameters.
func (in *PolicyL2VpnSessionTagParameters) DeepCopy() *PolicyL2VpnSessionTagParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyL2VpnSessionTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleObservation) DeepCopyInto(out *RuleObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NsxID != nil {
		in, out := &in.NsxID, &out.NsxID
		*out = new(string)
		**out = **in
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleObservation.
func (in *RuleObservation) DeepCopy() *RuleObservation {
	if in == nil {
		return nil
	}
	out := new(RuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParameters) DeepCopyInto(out *RuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParameters.
func (in *RuleParameters) DeepCopy() *RuleParameters {
	if in == nil {
		return nil
	}
	out := new(RuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagObservation) DeepCopyInto(out *TagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagObservation.
func (in *TagObservation) DeepCopy() *TagObservation {
	if in == nil {
		return nil
	}
	out := new(TagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagParameters) DeepCopyInto(out *TagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagParameters.
func (in *TagParameters) DeepCopy() *TagParameters {
	if in == nil {
		return nil
	}
	out := new(TagParameters)
	in.DeepCopyInto(out)
	return out
}
